# 1. Server Configuration
server.port=8080
spring.application.name=smart-finance-system

# 2. Database Configuration (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PersonalFinanceDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 3. JPA & Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 4. Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranthephong208@gmail.com
spring.mail.password=jghsdhmxmaffvqpg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 5. File Upload (D\uFFFDng cho avatar ho?c h\uFFFDa ??n sau n\uFFFDy)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# 6. Logging
logging.level.org.springframework.security=INFO

gemini.api.key=AIzaSyCV851I6nH9sTyo6_ETOs7bpjxVoiAvVBo
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# i18n Configuration
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# JWT Configuration
# Ch\u1EEF k\u00FD b\u00ED m\u1EADt (ph\u1EA3i d\u00E0i \u00EDt nh\u1EA5t 32 k\u00FD t\u1EF1, \u00F4ng g\u00F5 \u0111\u1EA1i d\u00F2ng n\u00E0o d\u00E0i d\u00E0i c\u0169ng \u0111\u01B0\u1EE3c)
jwt.secret=SmartFinanceSecretKeyForJwtAuthenticationFptUni123
# Th\u1EDDi gian s\u1ED1ng c\u1EE7a Token (t\u00EDnh b\u1EB1ng millisecond, v\u00ED d\u1EE5 86400000 = 24 ti\u1EBFng)
jwt.expiration=86400000